const IMG = {
  strings:      "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/4e19a3a12_Lengthscaleofstrings1Dinstringtheory.jpg",
  neutrinos:    "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/028fc2f7f_Effectivesizeofneutrinosthetiniestknownpieceofmatter.jpg",
  preons:       "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/f9875bc20_Predictedsizeofpreonsbuildingblocksofquarks.jpg",
  quarks:       "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/5627cf827_Effectivesizeofquarksbuildingblocksofprotonsandneutrons.jpg",
  proton:       "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/c82862d07_Comptonwavelengthofaproton.jpg",
  uranium:      "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/d7f69ef2b_DiameterofUraniumsnucleus.jpg",
  electron:     "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/57fe0ce4a_Comptonwavelengthofanelectron.jpg",
  bohr:         "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/bb63c858b_Bohrradiusofhydrogenatom.jpg",
  cesium:       "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/92c6edbc1_Radiusofthelargestknownatomcesiumourtimekeeper.jpg",
  dna:          "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/fe111501f_DiameteroftheDNAhelixourgeneticblueprint.jpg",
  rhinovirus:   "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/0e5282adb_Diameterofatypicalrhinovirusacommonvirusinhumans.jpg",
  skincell:     "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/cc6b98133_Diameterofahumanskincellkeratinocyte.jpg",
  rbc:          "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/718cf7b55_Diskdiameterofatypicalhumanredbloodcell.jpg",
  hair:         "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/62a3a5bf4_Minimumwidthofastrandofhumanhair.jpg",
  ovum:         "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/0e7b648cd_Typicaldiameterofahumanovum.jpg",
  pineal:       "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/5ec73ca16_Typicallengthoftheadultpinealgland.jpg",
  cornea:       "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/11705b9ce_Typicaldiameterofthecorneaofanadulteye.jpg",
  liver:        "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/3485fcd32_Typicallengthofanadultliver.jpg",
  room:         "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/aecb6cb84_Floortocellingdistanceinanaverageresidentialhome.jpg",
  pool:         "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/11e05d4ed_LengthofOlympicssizedswimmingpool.jpg",
  eiffel:       "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/2daf0ab52_HeightoftheEiffelTowerinclud-ingantenna.jpg",
  dam:          "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/25208f8ba_LengthofThreeGorgesDamthelargestdamintheworld.jpg",
  lhc:          "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/62469cb6a_CircumferenceofLargeHadronCollideraparticleaccelerator.jpg",
  iss:          "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/3a387d8c5_MaxaltitudeoftheInternationalSpaceStationfromEarth.jpg",
  greatwall:    "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/2a20327a7_LengthoftheGreatWallofChina.jpg",
  cable:        "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/52045fbd1_Lengthoflongestsubmarinecommunicationscable.jpg",
  moon:         "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/f745237ac_Farthesthumanshavetravelledtothefarsideofthemoon.jpg",
  sun:          "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/9e84cb284_DiameteroftheSunourhomestar.jpg",
  earthsun:     "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/a8acc0a0e_DistancefromtheEarthtotheSun.jpg",
  voyager:      "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/af27bb082_DistancetoVoyager1thefarthestspacecraftfromEarth.jpg",
  oort:         "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/49807c013_DiameteroftheSolarSystemsOortCloud.jpg",
  betelgeuse:   "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/613f28df3_DistancetoBetelgueseOrionsRedSupergiant.jpg",
  milkyway:     "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/f889df0a5_DiameteroftheMilkyWaygalacticdisk.jpg",
  localgroup:   "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/7f5e0805b_DiameterofourLocalGroupofgalaxies54galaxies.jpg",
  laniakea:     "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/2b5fb68da_DiameterofLaniakeaourlocalsupercluster100000galaxies.jpg",
  universe:     "https://media.base44.com/images/public/69edfb5b0aa2b16d4ea93b56/96d78d4bc_Co-movingdiameteroftheobserv-ableuniverse.jpg",
};

export const LEVELS = [
  {
    id: 0,
    name: "Subatomic to Molecular",
    difficulty: "Pro",
    difficultyColor: "text-red-400",
    range: "10⁻³⁵ to 10⁻¹⁰ m",
    description: "Objects from the particle universe. We can't see all these objects but can infer their existence and describe them with physical and mathematical models. The lines between particle length and wavelength blur here.",
    cards: [
      {
        id: "s1",
        name: "Length scale of strings (1D) in string theory",
        exponent: -35,
        coefficient: "1.62",
        metricLabel: "10⁻³⁵ m",
        metricConversion: "10⁻³⁵ m = Planck's length",
        image: IMG.strings,
      },
      {
        id: "s2",
        name: "Effective size of neutrinos, the tiniest known piece of matter",
        exponent: -24,
        coefficient: "2",
        metricLabel: "10⁻²⁴ m",
        metricConversion: "10⁻²⁴ m = 1 yoctometer (ym)",
        image: IMG.neutrinos,
      },
      {
        id: "s3",
        name: "Predicted size of preons, building blocks of quarks",
        exponent: -21,
        coefficient: "2",
        metricLabel: "10⁻²¹ m",
        metricConversion: "10⁻²¹ m = 1 zeptometer (zm)",
        image: IMG.preons,
      },
      {
        id: "s4",
        name: "Effective size of quarks, building blocks of protons and neutrons",
        exponent: -18,
        coefficient: "2",
        metricLabel: "10⁻¹⁸ m",
        metricConversion: "10⁻¹⁸ m = 1 attometer (am)",
        image: IMG.quarks,
      },
      {
        id: "s5",
        name: "Compton wavelength of a proton",
        exponent: -15,
        coefficient: "1.32",
        metricLabel: "10⁻¹⁵ m",
        metricConversion: "10⁻¹⁵ m = 1 femtometer (fm)",
        image: IMG.proton,
      },
      {
        id: "s6",
        name: "Diameter of Uranium's nucleus (92 protons, 143 neutrons)",
        exponent: -14,
        coefficient: "1.5",
        metricLabel: "10⁻¹⁴ m",
        metricConversion: "10⁻¹⁴ m = 100 picometer (pm)",
        image: IMG.uranium,
      },
      {
        id: "s7",
        name: "Compton wavelength of an electron",
        exponent: -12,
        coefficient: "2.4",
        metricLabel: "10⁻¹² m",
        metricConversion: "10⁻¹² m = 1 picometer (pm)",
        image: IMG.electron,
      },
      {
        id: "s8",
        name: "Bohr radius of hydrogen atom",
        exponent: -11,
        coefficient: "5.2",
        metricLabel: "10⁻¹¹ m",
        metricConversion: "10⁻¹¹ m = 10 picometers (pm)",
        image: IMG.bohr,
      },
      {
        id: "s9",
        name: "Radius of the largest known atom, cesium, our timekeeper",
        exponent: -10,
        coefficient: "2.98",
        metricLabel: "10⁻¹⁰ m",
        metricConversion: "10⁻¹⁰ m = 1 Ångström (Å)",
        image: IMG.cesium,
      },
    ]
  },
  {
    id: 1,
    name: "Molecular to Human",
    difficulty: "Medium",
    difficultyColor: "text-yellow-400",
    range: "10⁻⁹ to 10⁻¹ m",
    description: "Objects from the nano to the centimeter universe inside the human body. We've heard of these objects but cannot see all with our naked eye.",
    cards: [
      {
        id: "m1",
        name: "Diameter of the DNA helix, our genetic blueprint",
        exponent: -9,
        coefficient: "~2",
        metricLabel: "10⁻⁹ m",
        metricConversion: "10⁻⁹ m = 1 nanometer (nm)",
        image: IMG.dna,
      },
      {
        id: "m2",
        name: "Diameter of a typical rhinovirus, a common virus in humans",
        exponent: -8,
        coefficient: "~3",
        metricLabel: "10⁻⁸ m",
        metricConversion: "10⁻⁸ m = 10 nanometer (nm)",
        image: IMG.rhinovirus,
      },
      {
        id: "m3",
        name: "Diameter of a human skin cell (keratinocyte)",
        exponent: -7,
        coefficient: "~3",
        metricLabel: "10⁻⁷ m",
        metricConversion: "10⁻⁷ m = 100 nanometer (nm)",
        image: IMG.skincell,
      },
      {
        id: "m4",
        name: "Disk diameter of a typical human red blood cell",
        exponent: -6,
        coefficient: "8.2",
        metricLabel: "10⁻⁶ m",
        metricConversion: "10⁻⁶ m = 1 micrometer (µm)",
        image: IMG.rbc,
      },
      {
        id: "m5",
        name: "Minimum width of a strand of human hair",
        exponent: -5,
        coefficient: "1.7",
        metricLabel: "10⁻⁵ m",
        metricConversion: "10⁻⁵ m = 10 micrometer (µm)",
        image: IMG.hair,
      },
      {
        id: "m6",
        name: "Typical diameter of a human ovum",
        exponent: -4,
        coefficient: "1.2",
        metricLabel: "10⁻⁴ m",
        metricConversion: "10⁻⁴ m = 100 micrometer (µm)",
        image: IMG.ovum,
      },
      {
        id: "m7",
        name: "Typical length of the adult pineal gland",
        exponent: -3,
        coefficient: "~8",
        metricLabel: "10⁻³ m",
        metricConversion: "10⁻³ m = 1 millimeter (mm)",
        image: IMG.pineal,
      },
      {
        id: "m8",
        name: "Typical diameter of the cornea of an adult eye",
        exponent: -2,
        coefficient: "1.15",
        metricLabel: "10⁻² m",
        metricConversion: "10⁻² m = 1 centimeter (cm)",
        image: IMG.cornea,
      },
      {
        id: "m9",
        name: "Typical length of an adult liver",
        exponent: -1,
        coefficient: "1.6",
        metricLabel: "10⁻¹ m",
        metricConversion: "10⁻¹ m = 10 centimeter (cm)",
        image: IMG.liver,
      },
    ]
  },
  {
    id: 2,
    name: "Human to Astronomical",
    difficulty: "Easy",
    difficultyColor: "text-green-400",
    range: "10⁰ to 10⁸ m",
    description: "Objects humans have built through feats of science, technology, design & engineering. We've seen them in our daily lives or through photographs and videos and have a greater visual connection with them.",
    cards: [
      {
        id: "h1",
        name: "Floor to ceiling distance in an average residential home",
        exponent: 0,
        coefficient: "~2.4",
        metricLabel: "10⁰ m",
        metricConversion: "10⁰ m = 1 meter (m)",
        image: IMG.room,
      },
      {
        id: "h2",
        name: "Length of Olympics sized swimming pool",
        exponent: 1,
        coefficient: "5",
        metricLabel: "10¹ m",
        metricConversion: "10¹ m = 10 meter (m)",
        image: IMG.pool,
      },
      {
        id: "h3",
        name: "Height of the Eiffel Tower (including antenna)",
        exponent: 2,
        coefficient: "3.2",
        metricLabel: "10² m",
        metricConversion: "10² m = 100 meter (m)",
        image: IMG.eiffel,
      },
      {
        id: "h4",
        name: "Length of Three Gorges Dam, the largest dam in the world",
        exponent: 3,
        coefficient: "2.3",
        metricLabel: "10³ m",
        metricConversion: "10³ m = 1 kilometer (km)",
        image: IMG.dam,
      },
      {
        id: "h5",
        name: "Circumference of Large Hadron Collider, a particle accelerator",
        exponent: 4,
        coefficient: "2.7",
        metricLabel: "10⁴ m",
        metricConversion: "10⁴ m = 10 kilometer (km)",
        image: IMG.lhc,
      },
      {
        id: "h6",
        name: "Max altitude of the International Space Station from Earth",
        exponent: 5,
        coefficient: "4.35",
        metricLabel: "10⁵ m",
        metricConversion: "10⁵ m = 100 kilometer (km)",
        image: IMG.iss,
      },
      {
        id: "h7",
        name: "Length of the Great Wall of China",
        exponent: 6,
        coefficient: "6.25",
        metricLabel: "10⁶ m",
        metricConversion: "10⁶ m = 1,000 km = 1 Megameter (Mm)",
        image: IMG.greatwall,
      },
      {
        id: "h8",
        name: "Length of longest submarine communications cable",
        exponent: 7,
        coefficient: "~2",
        metricLabel: "10⁷ m",
        metricConversion: "10⁷ m = 10,000 km = 10 Mm",
        image: IMG.cable,
      },
      {
        id: "h9",
        name: "Farthest humans have travelled—to the far side of the moon",
        exponent: 8,
        coefficient: "~4",
        metricLabel: "10⁸ m",
        metricConversion: "10⁸ m = 100,000 km = 100 Mm",
        image: IMG.moon,
      },
    ]
  },
  {
    id: 3,
    name: "Astronomical to Cosmological",
    difficulty: "Hard",
    difficultyColor: "text-orange-400",
    range: "10⁹ to 10²⁶ m",
    description: "Astronomical objects like planets, moons, stars, galaxies, superclusters, and the observable universe. We've perhaps seen images, simulations, and videos of them, but these are rarely to scale.",
    cards: [
      {
        id: "a1",
        name: "Diameter of the Sun, our home star",
        exponent: 9,
        coefficient: "1.39",
        metricLabel: "10⁹ m",
        metricConversion: "10⁹ m = 1 million km = 1 Gigameter (Gm)",
        image: IMG.sun,
      },
      {
        id: "a2",
        name: "Distance from the Earth to the Sun",
        exponent: 11,
        coefficient: "1.5",
        metricLabel: "10¹¹ m",
        metricConversion: "10¹¹ × 1.5 m = 150 million km = 1 AU",
        image: IMG.earthsun,
      },
      {
        id: "a3",
        name: "Distance to Voyager 1, the farthest spacecraft from Earth",
        exponent: 13,
        coefficient: "2.11",
        metricLabel: "10¹³ m",
        metricConversion: "10¹³ × 2.11 m = 21.1 trillion km = 141 AU",
        image: IMG.voyager,
      },
      {
        id: "a4",
        name: "Diameter of the Solar System's Oort Cloud",
        exponent: 15,
        coefficient: "9.4",
        metricLabel: "10¹⁵ m",
        metricConversion: "10¹⁵ × 9.4 m = 1 light year (ly)",
        image: IMG.oort,
      },
      {
        id: "a5",
        name: "Distance to Betelguese, Orion's Red Supergiant",
        exponent: 18,
        coefficient: "6.07",
        metricLabel: "10¹⁸ m",
        metricConversion: "10¹⁸ × 6.07 m = 645 light years (ly)",
        image: IMG.betelgeuse,
      },
      {
        id: "a6",
        name: "Diameter of the Milky Way galactic disk",
        exponent: 20,
        coefficient: "9.5",
        metricLabel: "10²⁰ m",
        metricConversion: "10²⁰ × 9.5 m = 100,000 light years (ly)",
        image: IMG.milkyway,
      },
      {
        id: "a7",
        name: "Diameter of our Local Group of galaxies (~54 galaxies)",
        exponent: 22,
        coefficient: "5",
        metricLabel: "10²² m",
        metricConversion: "10²² × 5 m = 10 million light years (ly)",
        image: IMG.localgroup,
      },
      {
        id: "a8",
        name: "Diameter of Laniakea, our local supercluster (~100,000 galaxies)",
        exponent: 24,
        coefficient: "5.9",
        metricLabel: "10²⁴ m",
        metricConversion: "10²⁴ × 5.9 m = 520 million light years (ly)",
        image: IMG.laniakea,
      },
      {
        id: "a9",
        name: "Co-moving diameter of the observable universe",
        exponent: 26,
        coefficient: "8.79",
        metricLabel: "10²⁶ m",
        metricConversion: "10²⁶ × 8.79 m = 93 billion light years (ly)",
        image: IMG.universe,
      },
    ]
  }
];